files:
  include: "src/**/*.scss"
  ignore:
    - node_modules/**

rules:
  property-sort-order: 0
  no-css-comments: 1
  class-name-format:
    - 1
    - convention: hyphenatedbem
  space-after-comma: 1
  leading-zero: 1
  quotes: 1
  empty-line-between-blocks:
    - 1
    - include: true
    - allow-single-line-rulesets: false
  placeholder-in-extend: 1
  no-transition-all: 1
  no-vendor-prefixes: 1
  pseudo-element: 1
  shorthand-values: 1
  no-color-literals: 1
  nesting-depth:
    - 1
    - max-depth: 2
  no-important: 1
  indentation:
    - 1
    - size: 2
  hex-length: 1
  final-newline: 1
  no-mergeable-selectors : 1
